### ISSUE TITLE
rk3step mechanics

### ISSUE THREAD

**Issue by jiskattema** [jiskattema/dales#2]
In modbulkmicro3, I'm taking a shortcut with sv0 == svm when rk3step = 1.
Is that correct?

**Comment by jchylik** [comment]
Yes, that should be correct, as long as the value sv0 is not "corrected" by some subroutine in other modules.

**Comment by jiskattema** [comment]
thanks. I've decide to not use the shortcut: it would add some non-obvious dependencies for a minor speedup
