### ISSUE TITLE
bulkmicro3: sedimentation limits

### ISSUE THREAD

**Issue by jiskattema** [jiskattema/dales#5]
What are the correct limits to start sedimentation in sedim_cl3, sedim_graupel3, sedim_ice3, sedim_rain3, sedim_snow3?

**Comment by jchylik** [comment]
It seem that there are not "correct limits", the thresholds were there originally to avoid extra calculation. Today, qip_min could be set to 0.

**Comment by jiskattema** [comment]
In that case, i'm taking the same limits as in the correct_neg_qt subroutine,
as any amount smaller will be removed there.

A non-zero threshold will speed up the sedimentation calculations in case there is nothing to sediment.
