### ISSUE TITLE
microphysics output: MPI optimization

### ISSUE THREAD

**Issue by jiskattema** [jiskattema/dales#9]
we use slabsum(), ie. mpi_allreduce, in the dobulkmicrostat routine. This is called every idtav seconds.

However, we only need the result in writebulkmicrostat, which is called itimeav seconds.

If itimeav > idtav, which seems likely, we can reduce communication by moving the slabsum() calls to writebulkmicrostat.

**Comment by jchylik** [comment]
Yes, that is a very good point. Is should apply to all variables calculated in dobulkmicrostat.

**Comment by jiskattema** [comment]
applied this to the new scheme.
